package com.componentes;

import com.classes.NumberToLetterConverter;
import com.document.NumberDocument;

public class CustomPanel extends javax.swing.JPanel {

    private final int NUMBER;

    public CustomPanel(int number) {
        NUMBER = number;
        initComponents();
        setValues();
    }

    public int getNumber() {
        return this.NUMBER;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        lblTitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(274, 157));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        topPanel.setPreferredSize(new java.awt.Dimension(274, 116));
        topPanel.setLayout(null);

        lblTitulo2.setText("Su número es:");
        topPanel.add(lblTitulo2);
        lblTitulo2.setBounds(20, 60, 90, 14);

        txtTexto.setEditable(false);
        topPanel.add(txtTexto);
        txtTexto.setBounds(20, 80, 220, 20);

        txtNumero.setDocument(new NumberDocument(3));
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        topPanel.add(txtNumero);
        txtNumero.setBounds(20, 30, 220, 20);

        lblTitulo1.setText("Ingrese un número:");
        topPanel.add(lblTitulo1);
        lblTitulo1.setBounds(20, 10, 130, 14);

        add(topPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloPrincipal.setText("jLabel1");
        jPanel1.add(lblTituloPrincipal);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        mostrarNumero();
    }//GEN-LAST:event_txtNumeroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables

    private void setValues() {
        lblTituloPrincipal.setText("# " + NUMBER);
    }

    private void mostrarNumero() {
        if (txtNumero.getText().trim().length() > 0) {
            String texto = NumberToLetterConverter.convertNumberToLetter(Integer.parseInt(txtNumero.getText()));
            txtTexto.setText(texto);
        }
    }
}
