package com.componentes;

import com.document.NumberDocument;
import javax.swing.JFrame;

public class DeleteDialog extends javax.swing.JDialog {

    private int option;
   
    public DeleteDialog(JFrame frame) {
        super(frame, true);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOption = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(232, 134));

        jPanel1.setPreferredSize(new java.awt.Dimension(226, 111));
        jPanel1.setLayout(null);

        txtOption.setDocument(new NumberDocument(3));
        jPanel1.add(txtOption);
        txtOption.setBounds(20, 30, 160, 20);

        lblTitle.setText("Ingrese el panel que desea borrar");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(20, 10, 170, 14);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(30, 30));

        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       borrar();
    }//GEN-LAST:event_btnDeleteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtOption;
    // End of variables declaration//GEN-END:variables

    private void borrar() {
        option = Integer.parseInt(txtOption.getText().trim());
        dispose();
    }

    public int getOption() {
        return option;    
    }
}
